# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'stock_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'stock_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  stock_dbt:
    # Apply default materialization settings for this project
    +materialized: view
    
    # Configure specific folders under models/
    raw_data:
      +materialized: view  # Use view for raw_data models
    tranformations:         # Matches your folder name exactly
      +materialized: table  # Use tables for tranformations models
